version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  flyway:
    image: flyway/flyway:latest
    environment:
      FLYWAY_URL: jdbc:postgresql://db/mydatabase
      FLYWAY_USER: myuser
      FLYWAY_PASSWORD: mypassword
    volumes:
      - ./sql:/flyway/sql
    depends_on:
      - db
    command: -connectRetries=10 -baselineOnMigrate=true migrate
